# database/create_schema.py
from oracle_connection import get_connection

def create_tables():
    conn = get_connection()
    if not conn:
        return

    cursor = conn.cursor()

    try:
        cursor.execute("""
        CREATE TABLE banks (
            bank_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            bank_name VARCHAR2(100) UNIQUE
        )
        """)

        cursor.execute("""
        CREATE TABLE reviews (
            review_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            bank_id NUMBER,
            review_date DATE,
            rating NUMBER,
            cleaned_text CLOB,
            sentiment_label VARCHAR2(20),
            sentiment_score FLOAT,
            FOREIGN KEY (bank_id) REFERENCES banks(bank_id)
        )
        """)

        print("Tables created successfully.")

    except Exception as e:
        print("Error creating tables:", e)

    conn.commit()
    cursor.close()
    conn.close()

if __name__ == "__main__":
    create_tables()